=begin
#Cheminée

#Cheminée: The Chemical Structure Search Engine

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0-SNAPSHOT

=end

module Cheminee
  VERSION = '0.1.39'
end
