=begin
#Cheminée

#Cheminée: The Chemical Structure Search Engine

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
Generator version: 7.8.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cheminee::ConvertedMolBlock
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cheminee::ConvertedMolBlock do
  let(:instance) { Cheminee::ConvertedMolBlock.new }

  describe 'test an instance of ConvertedMolBlock' do
    it 'should create an instance of ConvertedMolBlock' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Cheminee::ConvertedMolBlock)
    end
  end

  describe 'test attribute "mol_block"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
