=begin
#Cheminée

#Cheminée: The Chemical Structure Search Engine

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cheminee::QueryResponseError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cheminee::QueryResponseError do
  let(:instance) { Cheminee::QueryResponseError.new }

  describe 'test an instance of QueryResponseError' do
    it 'should create an instance of QueryResponseError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Cheminee::QueryResponseError)
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
