=begin
#Cheminée

#Cheminée: The Chemical Structure Search Engine

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cheminee::QuerySearchHit
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cheminee::QuerySearchHit do
  let(:instance) { Cheminee::QuerySearchHit.new }

  describe 'test an instance of QuerySearchHit' do
    it 'should create an instance of QuerySearchHit' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Cheminee::QuerySearchHit)
    end
  end

  describe 'test attribute "extra_data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "smiles"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "query"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
