=begin
#Cheminée

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cheminee::Smile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cheminee::Smile do
  let(:instance) { Cheminee::Smile.new }

  describe 'test an instance of Smile' do
    it 'should create an instance of Smile' do
      expect(instance).to be_instance_of(Cheminee::Smile)
    end
  end
  describe 'test attribute "smile"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
