=begin
#Cheminée

#Cheminée: The Chemical Structure Search Engine

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Cheminee::StandardizedSmile
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Cheminee::StandardizedSmile do
  let(:instance) { Cheminee::StandardizedSmile.new }

  describe 'test an instance of StandardizedSmile' do
    it 'should create an instance of StandardizedSmile' do
      expect(instance).to be_instance_of(Cheminee::StandardizedSmile)
    end
  end
  describe 'test attribute "smile"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
