=begin
#Cheminée

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

# Common files
require 'cheminee/api_client'
require 'cheminee/api_error'
require 'cheminee/version'
require 'cheminee/configuration'

# Models
require 'cheminee/models/smile'

# APIs
require 'cheminee/api/default_api'

module Cheminee
  class << self
    # Customize default settings for the SDK using block.
    #   Cheminee.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
